baseURL = "https://patrickcanal.xyz/"
languageCode = "en-us"
title = "Patrick Canal"
theme = "ficurinia"
copyright = "Patrick Canal"

[params]
author = "Patrick Canal"

logo = "/logo.svg"
svgicon = "/logo.svg"

enableJumbotron = true
infiniteScrolling = true

[menu]
[[menu.icons]]
identifier = "github"
name = "Github"
url = "https://github.com/Superredstone"
weight = 10

[outputs]
home = ["HTML", "JSON"]
